---
# This builds out the initial users and groups for the rocky linux infra
- name: Create our initial users
  hosts: ipaserver
  become: false
  vars_files:
  - vars/encpass.yml
  - vars/users.yml
  - vars/groups.yml

  tasks:
    - name: "Checking for user variables"
      assert:
        that:
          - ipaadmin_password | mandatory
          - users | mandatory
          - ipagroups | mandatory
        success_msg: "Required variables provided"
        fail_msg: "We are missing users or ipa admin password"

    - name: "Start users"
      import_playbook: import-rockyusers.yml

    - name: "Start groups"
      import_playbook: import-rockygroups.yml

    - name: "Start sudo for admins"
      import_playbook: import-rockysudo.yml
